### ISSUE TITLE
リアルタイムチャット実装

### ISSUE THREAD

**Issue by henacken** [henacken/kstm#1]
### リアルタイムチャット実装

**Comment by nona-takahara** [comment]
- [x] Next.js標準APIやそれに準ずるものとカスタムサーバの同居状態を作成
- [x] WebSocketのコネクションを張れるようにする
- [x] とりあえず投稿者不明・ログ無しリアルタイムチャットを起こす
- [x] （ログイン機能？　これは他の仕組みと連携必須）
- [ ] 鍵つきセッション（仮にルームと呼ぶ）の仕組みを導入する

**Comment by nona-takahara** [comment]
この投稿をメモ兼用にします　通知がうるさかったら教えてください。

- Discordでの認識すり合わせを行ってから、タスク2までを別Issueに分離
- https://www.treefrogframework.org/ja/user-guide/websocket/

**Comment by nona-takahara** [comment]
いったん閉じて続きは別Issueにします
